let g:pdv_cfg_Type = "mixed"
let g:pdv_cfg_Package = "Kohort_"
let g:pdv_cfg_Category = ""
let g:pdv_cfg_Version = "Release: 0.1.0.2"
let g:pdv_cfg_Author = "Ben Weller <ben@kohort.com>"
let g:pdv_cfg_Copyright = "2011 Kohort, Inc."
let g:pdv_cfg_License = "None: Confidential and Proprietary"
let g:pdv_cfg_Link = "http://kohort.com" 
